[package]
name = "dummy_project"
version = "0.1.0"
authors = ["Neil Kaushikkar <neil.kaushikkar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
textplots = "0.6"